FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install --no-fund --no-audit

COPY . .

ARG NEXT_PUBLIC_NAKAMA_SERVER_KEY=local-nakama-server-key
ARG NEXT_PUBLIC_NAKAMA_HOST=127.0.0.1
ARG NEXT_PUBLIC_NAKAMA_PORT=7350
ARG NEXT_PUBLIC_NAKAMA_USE_SSL=false

ENV NEXT_PUBLIC_NAKAMA_SERVER_KEY=$NEXT_PUBLIC_NAKAMA_SERVER_KEY
ENV NEXT_PUBLIC_NAKAMA_HOST=$NEXT_PUBLIC_NAKAMA_HOST
ENV NEXT_PUBLIC_NAKAMA_PORT=$NEXT_PUBLIC_NAKAMA_PORT
ENV NEXT_PUBLIC_NAKAMA_USE_SSL=$NEXT_PUBLIC_NAKAMA_USE_SSL

RUN npm run build

EXPOSE 3000
CMD ["npm", "start"]
